// front/src/components/SideBar.vue
<template>
    <aside class="border-r border-neutral-500/20 transition-[width] duration-200" :class="collapsed
        ? 'w-12'
        : 'w-48'">
        <!-- <div class="justify-between flex items-center">
        {#if !collapsed}
            <div class="p-4 text-neutral-300 text-sm">Image Master</div>
        {/if} -->
        <div class="border-b border-neutral-500/20">
            <button class="p-4 hover:bg-neutral-700/50 transition-colors duration-200 cursor-pointer"
                @click="collapsed = !collapsed">
                <AlignJustify class="w-4 h-4 text-neutral-300" />
            </button>
        </div>
        <!-- </div> -->

        <div class="border-b border-neutral-500/20">
            <template v-for="menu in menuList" :key="menu.path">
                <button @click="router.push(menu.path)" :class="`relative w-full hover:bg-neutral-700/50 transition-colors duration-200 cursor-pointer ${menu.active
                    ? 'bg-neutral-700/50'
                    : ''}`">
                    <template v-if="menu.active">
                        <div
                            class="absolute left-0 top-0 w-0.5 h-full rounded-full bg-blue-500 transition-all duration-500 animate-shrink">
                        </div>
                    </template>
                    <div class="p-4 flex items-center gap-2">
                        <component :is="menu.icon" class="w-4 h-4 text-neutral-300" />
                        <Transition >
                            <span v-if="!collapsed" class="text-neutral-300 text-xs ml-2">{{ menu.label }}</span>
                        </Transition>
                    </div>
                </button>
            </template>
        </div>
    </aside>
</template>

<script setup lang="ts">
import { AlignJustify, Download, Home, Settings } from "lucide-vue-next";
import { computed, ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();

let collapsed = ref(false);

let menuList = computed(() => [
    {
        icon: Home,
        label: "Home",
        path: "/",
        active: router.currentRoute.value.path === "/",
    },
    {
        icon: Download,
        label: "Download",
        path: "/download",
        active: router.currentRoute.value.path === "/download",
    },
    {
        icon: Settings,
        label: "Setting",
        path: "/setting",
        active: router.currentRoute.value.path === "/setting",
    },

]);
</script>

<style scoped>
.v-enter-active,
.v-leave-active {
    transition: all 0.5s ease;
}

.v-enter-from,
.v-leave-to {
    position: absolute;
    opacity: 0;
    transform: translateX(-20px);
}
</style>

// frontend/src/components/SideBar.svelte
<script lang="ts">
    import { AlignJustify, Download, Home, Settings } from "lucide-svelte";
    import { fade, fly } from "svelte/transition";
    import { push } from "svelte-spa-router";
    import { location } from "svelte-spa-router";

    let collapsed = $state(false);

    let menuList = $derived([
        {
            icon: Home,
            label: "Home",
            path: "/",
            active: $location === "/",
        },
        {
            icon: Download,
            label: "Download",
            path: "/download",
            active: $location === "/download",
        },
        {
            icon: Settings,
            label: "Setting",
            path: "/setting",
            active: $location === "/setting",
        },
        
    ]);
</script>

<aside
    class="{collapsed
        ? 'w-12'
        : 'w-48'} border-r border-neutral-500/20 transition-all duration-200"
>
    <!-- <div class="justify-between flex items-center">
        {#if !collapsed}
            <div class="p-4 text-neutral-300 text-sm">Image Master</div>
        {/if} -->
    <div class="border-b border-neutral-500/20">
        <button
            class="p-4 hover:bg-neutral-700/50 transition-colors duration-200 cursor-pointer"
            onclick={() => (collapsed = !collapsed)}
        >
            <AlignJustify class="w-4 h-4 text-neutral-300" />
        </button>
    </div>
    <!-- </div> -->

    <div class="border-b border-neutral-500/20">
        {#each menuList as menu}
            <button
                class="relative w-full hover:bg-neutral-700/50 transition-colors duration-200 cursor-pointer {menu.active
                    ? 'bg-neutral-700/50'
                    : ''}"
                onclick={() => {
                    push(menu.path);
                }}
            >
                {#if menu.active}
                    <div
                        class="absolute left-0 top-0 w-0.5 h-full rounded-full bg-blue-500 transition-all duration-500 animate-shrink"
                    ></div>
                {/if}
                <div class="p-4 flex items-center gap-2">
                    <menu.icon class="w-4 h-4 text-neutral-300" />
                    {#if !collapsed}
                        <span
                            in:fly={{ x: -50 }}
                            class="text-neutral-300 text-xs ml-2"
                            >{menu.label}</span
                        >
                    {/if}
                </div>
            </button>
        {/each}
    </div>
</aside>

<style>

</style>
